"""Rust-core parity: `stint parity …` must match the bash oracle exactly where
`stintcore.engine` does, and diverge exactly where it (intentionally) does.

Same grid and same oracle as test_parity.py, driven through the compiled
binary. The binary is located via $STINT_BIN, then target/{debug,release};
the module is skipped when none exists, so a Python-only checkout stays green.
Where `bc` is missing (Windows, macOS) the oracle's outputs come from
tests/oracle_snapshot.json, regenerated on Linux/WSL by gen_oracle_snapshot.py.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from datetime import datetime, timedelta
from decimal import Decimal
from pathlib import Path

import pytest

from test_parity import _LEGACY_ROUNDING_DIVERGENCES, _PARITY_SECONDS, _BASE, _ts
from test_parity import _oracle as _live_oracle

_REPO = Path(__file__).resolve().parent.parent
_SNAPSHOT = Path(__file__).parent / "oracle_snapshot.json"

# The live oracle needs bc (Linux/WSL). Elsewhere, fall back to the snapshot
# generated by gen_oracle_snapshot.py so parity is still asserted byte-for-byte.
_HAVE_BC = shutil.which("bc") is not None
_SNAP = json.loads(_SNAPSHOT.read_text(encoding="utf-8")) if _SNAPSHOT.exists() else None


def _oracle(kind: str, *args: str) -> str:
    if _HAVE_BC:
        return _live_oracle(kind, *args)
    if _SNAP is None:
        pytest.skip("no bc and no tests/oracle_snapshot.json")
    if kind == "hrs":
        secs = int((datetime.strptime(args[1], "%Y-%m-%d %H:%M:%S") - _BASE).total_seconds())
        return _SNAP["hrs"][str(secs)]
    if kind == "row":
        _date, start, end, cat, desc = args
        secs = int((datetime.strptime(end, "%Y-%m-%d %H:%M:%S") - _BASE).total_seconds())
        return _SNAP["row"][f"{secs}|{cat}|{desc}"]
    if kind == "bill":
        return _SNAP["bill"][args[0]]
    raise KeyError(kind)


def _find_binary() -> Path | None:
    env = os.environ.get("STINT_BIN")
    if env and Path(env).exists():
        return Path(env)
    for profile in ("debug", "release"):
        for name in ("stint", "stint.exe"):
            p = _REPO / "target" / profile / name
            if p.exists():
                return p
    return None


_BIN = _find_binary()
pytestmark = pytest.mark.skipif(_BIN is None, reason="stint binary not built (cargo build)")


def _stint(*args: str) -> str:
    return subprocess.run(
        [str(_BIN), "parity", *args],
        capture_output=True,
        text=True,
        check=True,
        encoding="utf-8",
    ).stdout.rstrip("\n")


@pytest.mark.parametrize("secs", _PARITY_SECONDS)
def test_rust_duration_matches_bash(secs: int) -> None:
    start = _ts(_BASE)
    end = _ts(_BASE + timedelta(seconds=secs))
    assert _stint("hrs", start, end) == _oracle("hrs", start, end)


@pytest.mark.parametrize("secs", _PARITY_SECONDS)
def test_rust_stop_row_matches_bash(secs: int) -> None:
    start, end = _ts(_BASE), _ts(_BASE + timedelta(seconds=secs))
    desc = "PR #129 review — diff + cross-repo audit (example-org/example-repo)"
    date = _BASE.strftime("%Y-%m-%d")
    assert _stint("row", date, start, end, "pr", desc) == _oracle("row", date, start, end, "pr", desc)


@pytest.mark.parametrize(
    "desc",
    [
        "plain description",
        "has, commas, in it",
        "em — dash narrative — with, comma",
        "T10 scraper impl (example-org/example-repo)",
        "unicode: résumé café Nguyễn",
    ],
)
def test_rust_description_passthrough_matches_bash(desc: str) -> None:
    start, end = _ts(_BASE), _ts(_BASE + timedelta(minutes=40))
    assert _stint("row", "2026-07-08", start, end, "dev", desc) == _oracle("row", "2026-07-08", start, end, "dev", desc)


@pytest.mark.parametrize("hrs", ["0.25", "0.50", "0.67", "1.07", "6.18", "42.10", "0.10", "100.00"])
def test_rust_billable_matches_bash(hrs: str) -> None:
    assert _stint("bill", hrs) == _oracle("bill", hrs)


@pytest.mark.parametrize("secs", sorted(_LEGACY_ROUNDING_DIVERGENCES))
def test_rust_shares_the_documented_bash_divergence(secs: int) -> None:
    """Rust must land on the *correct* side, exactly like the Python port."""
    from stintcore import engine

    start, end = _ts(_BASE), _ts(_BASE + timedelta(seconds=secs))
    rust = _stint("hrs", start, end)
    assert rust == engine.duration_hrs(start, end)
    assert rust != _oracle("hrs", start, end)
    assert abs(Decimal(rust) - Decimal(_oracle("hrs", start, end))) == Decimal("0.01")


def test_rust_binary_runs() -> None:
    """Catches a binary that built but can't load (e.g. a missing runtime DLL)."""
    out = subprocess.run([str(_BIN), "--version"], capture_output=True, text=True)
    assert out.returncode == 0, out.stderr
    assert out.stdout.startswith("stint ")
